# Generated by Django 3.1.7 on 2021-03-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_whishlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhishListItem',
            new_name='WishListItem',
        ),
    ]
