# Generated by Django 3.1.7 on 2021-03-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0003_auto_20210318_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='price',
        ),
    ]
