# Generated by Django 3.1.7 on 2021-03-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0004_remove_wishlistitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop1.customer'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop1.product'),
        ),
    ]
