# Generated by Django 3.1.7 on 2021-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0006_auto_20210318_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
