# Generated by Django 3.1.7 on 2021-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0008_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
