# Generated by Django 3.1.2 on 2021-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0009_auto_20210405_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
