# Generated by Django 3.1.2 on 2021-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
